#cloud-config

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCrV5qXWu91sYSv8xuKmOGFJkomU3ly4JD1kySV/qS0z5K8Fog6jrZMebRpEQrGqgEoBFnlA1A0FZ8M+WHQf2n1JjnYZHRnNjnXrO2PiW1O8yRZgULuP5IHQaDI9Gbah7TwdJ7sYuvkE5oMYE1T/Tv8oK4kh1oQ8SME3gfIiZHh85raWKtS+3n0MGQrhRnwbAzk+0zwVL5p8P85inY9512j/XQhSLrALskXy4SPXV04jhRjMQcF1gBGhjIRlr7wskSfHgoWLyvtpSiuJ6TJ8cPD3UuzybOVvhGaRiI5TvGht1+1nuoXbmZv46ZiAe/0MUJJq0yy1PPTcZISff0ZgmoVpyAOtpWYrrIDeYM+NWTc7hK3jB4qeLmhTiEHR/cZlKvnPIU5+rrrrQO/xMlncogVTbohiqtOb6Vc4F6aYDU1oVMeD6WcIfPrnViGCBNHV2oDoS6EtwxmXYfHpChcN7ZOXQUwujdFSir/xMrUIidK7N//ItGK8eUIUjToCOARKl0= one\lohy@MYKUL1LT024

hostname: my-rancher-host

rancher:
  network:
    interfaces:
      eth*:
        dhcp: true
  services:
    rancher-server:
      image: rancher/rancher:stable
      restart: unless-stopped
      privileged: true
      ports:
        - 80:80
        - 443:443
      environment:
      - CATTLE_BOOTSTRAP_PASSWORD: my-rancher-password
