#cloud-config

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDamzQLMYYlH1L9DjHUPn6hVbne7OFB3DWVueld29w9llZ3BznAC4ZigiXh67Z+N6FKjvFFArGWfI8b/12cAOV8FlCTwq3WIya3fxZWhOt8QTDKlVPhwhWblwBu5UqYcRH5m6bnuqiqzTuTnDfkMk2/akJfcjL/ckQWQh5eEEPDBtj/GnRBRgZz1azqg0fijkV3Q6j9MvccrGhMBnZlRzS2JGcJ59SEN9KCYQlo5j/AHKb4lOOIsZEJ005WGLmVDuomZkLksbRLYuosjcXnQ8d4w0qZYWJklSFWTNxQx7uZwh5Md2IHcZEch7tesg37R/B0huF0kDUcghMY0lwjIJH9Neq9hdCN10jIMW8cY5XXAub6vv4XnLWn1lXWJ7kZWEUzPbDjkzLLYqTa7TNnP8Pb06CYqpP3c1QiPEOQFIl8MGkbF7HHXvnZPep+kBec1OvsP+ff8gyc8IAFD11QpGxlgc71eBiW66isi3XCw8ocGIIepX5hvt3W+DE2lJM/nMSrvszozfKdFDNy0tEAxrebk7O+c6p6SMA83XMi4zjWKJhDhCjdOP25uzz54xSXtK+l5/IbliUs+MWU9m+bxmVkrMAJGM3EhnRC6yUHoQsIkgj7Izhm519AXVYpGJSU9qkFeLTGwpsKrSR3mBHsT90u7yJl053Rr6VwzUtBh0Uepw== hengyu.lo@grassvalley.com

hostname: my-rancheros-host

rancher:
  network:
    interfaces:
      eth*:
        dhcp: true
  services:
    rancher-server:
      image: rancher/rancher:latest
      restart: unless-stopped
      command:
      - --privileged
      ports:
        - 80:80
        - 443:443
